# Change these first
owner: jaimehisao # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: Zeus API
    url: $ZEUS_API

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.hisao.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Hisao.org Status Page
  introTitle: "**Hisao.org & Services**"
  introMessage: Status page for Hisao's Services
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
